ERROR: fixedTree copying from workTree
	when copying from "worktree" to FixedTree_self,
	wasnt updating .tree.data ptr
	err caused a bunch of weird memory stuff later ofc